### ISSUE TITLE
GCD/LCM/Fraction Stuff

### ISSUE THREAD

**Issue by chipbell4** [MercerBinaryBears/ReferenceSheet#8]

**Comment by thekenton** [comment]
Hancock, Foster, and Kenton - Python

**Comment by JakeFoster1** [comment]
[gcd-lcm.txt](https://github.com/MercerBinaryBears/ReferenceSheet/files/557244/gcd-lcm.txt)

**Comment by JakeFoster1** [comment]
[convert-base.txt](https://github.com/MercerBinaryBears/ReferenceSheet/files/557245/convert-base.txt)

**Comment by JakeFoster1** [comment]
[checking-primes.txt](https://github.com/MercerBinaryBears/ReferenceSheet/files/557247/checking-primes.txt)

**Comment by thekenton** [comment]
[Fraction_Reduction.txt](https://github.com/MercerBinaryBears/ReferenceSheet/files/557256/Fraction_Reduction.txt)

**Comment by thekenton** [comment]
[Decimal_to_Fraction.txt](https://github.com/MercerBinaryBears/ReferenceSheet/files/557262/Decimal_to_Fraction.txt)
